---
title: "class08"
author: "Megan Watson"
date: "2026-09-21"
output: 
  html_document:
    toc: true
    toc_float: true 
    number_sections: true 
    code_download: true 
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r slide08}
httr2::request("https://data.cincinnati-oh.gov/resource/rvmt-pkmq.json") |>
  httr2::req_url_query("$limit" = 5) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON()
```


```{r fred}
ohio_jobs = 
  httr2::request("https://api.stlouisfed.org/fred/series/observations") |>
  httr2::req_url_query(
    series_id = "IHLIDXUSOH",
    api_key = Sys.getenv("FRED_API_KEY"),
    file_type = "json"
  ) |>
  # nothing has been sent yet
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON()

dplyr::glimpse(ohio_jobs)

ohio_df = ohio_jobs$observations # we saw that the data is in observations 

dplyr::glimpse(ohio_df)

# another approach to filter the dates would be:
ohio_df |>
  # overwrite the date column and convert to date (from chr)
  dplyr::mutate(date = lubridate::ymd(date)) |>
  # bc it is a date, we can do logical checks on it and keep dates from sep 01, 2026
  dplyr::filter(date >= '2026-09-01') -> ohio_df_sept_2026

```
```{r usajobs}
httr2::request("https://data.usajobs.gov/api/search") |>
  httr2::req_url_query(Keyword = "Data Analyst", ResultsPerPage = 500) |>
  httr2::req_headers(
    Host = "data.usajobs.gov",
    "User-Agent" = "yourname@miamioh.edu",
    "Authorization-Key" = Sys.getenv("USAJOBS_API_KEY")
  ) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON(flatten = TRUE) -> usa_jobs_data

usa_jobs_df = usa_jobs_data$SearchResult$SearchResultItems

jobs_small = usa_jobs_df |>
  dplyr::select(
    title = MatchedObjectDescriptor.PositionTitle,
    department = MatchedObjectDescriptor.DepartmentName,
    agency = MatchedObjectDescriptor.OrganizationName,
    location = MatchedObjectDescriptor.PositionLocationDisplay,
    closes = MatchedObjectDescriptor.ApplicationCloseDate
  )

## easy way - since we looked for data analyst as a key word 
nrow(jobs_small)
## q 2
table(jobs_small$department) |> sort(decreasing = T)
jobs_small |> dplyr::count(department) |>
  dplyr::arrange(dplyr::desc(n)) |> head(3)

## the harder way (but being literal)
jobs_small |> dplyr::filter(title == 'Data Analyst') -> count_literal
count_literal |> dplyr::count(department) |>
  dplyr::arrange(dplyr::desc(n))

## the harder way (without being literal)
# jesse -> Data analyst or data analytics side-by-side
index_data_analyst = jobs_small$title |>
  stringr::str_detect("Data Analytics|Data Analyst")

# given that this is a true or false tyoe result 
# true rows will be kepts
# ', nothing' means keep all columns 
count_jesse_standard = jobs_small[index_data_analyst, ]
view(count_jesse_standard)

```

